log:
  level: debug
  disable_sentry: true

db:
  url: postgres://slug:slug@127.0.0.1:55432/slugsvc?sslmode=disable

listener:
  addr: :8000

shortener:
  base_url: 'http://localhost:8000/integrations/slug-svc'
  storage: 'pg' # pg | memory

cop:
  disabled: true
  endpoint: 'http://...'
  upstream: 'http://...'
  service_name:
  service_port: 80
